// General header for all component includes

// This header was generated by the serialiation code generation program

#ifndef MVG_COMPONENTS_HPP_
#define MVG_COMPONENTS_HPP_

#include "Components/BoxCollider.hpp"
#include "Components/Button.hpp"
#include "Components/Camera.hpp"
#include "Components/CameraZoomController.hpp"
#include "Components/Canvas.hpp"
#include "Components/ClickEffect.hpp"
#include "Components/ColliderRenderer.hpp"
#include "Components/DirectionalLight.hpp"
#include "Components/DoNotSerialize.hpp"
#include "Components/EditorCameraController.hpp"
#include "Components/FPSCameraController.hpp"
#include "Components/FreeLookController.hpp"
#include "Components/Image.hpp"
#include "Components/MusicController.hpp"
#include "Components/Name.hpp"
#include "Components/OutlineRenderer.hpp"
#include "Components/ParticleEmitter.hpp"
#include "Components/PointLight.hpp"
#include "Components/Rigidbody.hpp"
#include "Components/Rotator.hpp"
#include "Components/Sound.hpp"
#include "Components/SoundListener.hpp"
#include "Components/SpotLight.hpp"
#include "Components/StaticMesh.hpp"
#include "Components/Text.hpp"
#include "Components/Transform.hpp"

#endif
