// General header for all component includes

// This header was generated by the serialiation code generation program

#ifndef MVG_COMPONENTS_HPP_
#define MVG_COMPONENTS_HPP_

#include "Components/Camera.hpp"
#include "Components/CameraZoomController.hpp"
#include "Components/DirectionalLight.hpp"
#include "Components/FPSCameraController.hpp"
#include "Components/FreeLookController.hpp"
#include "Components/Material.hpp"
#include "Components/ParticleEmitter.hpp"
#include "Components/PointLight.hpp"
#include "Components/Rigidbody.hpp"
#include "Components/Rotator.hpp"
#include "Components/SpotLight.hpp"
#include "Components/StaticMesh.hpp"
#include "Components/Transform.hpp"

#endif
