// General header for all component includes

// This header was generated by the serialiation code generation program

#ifndef MVG_COMPONENTS_HPP_
#define MVG_COMPONENTS_HPP_

{{#IncludeComponentFile}}
#include "Components/{{ComponentName}}.hpp"
{{/IncludeComponentFile}}

#endif
