#include "Serialization/ComponentMetaInfo.hpp"

namespace Saturn::Meta::detail {

// This function was generated by SaturnEngine
void init_component_meta_data(std::vector<ComponentInfo>& data) {
	{
		ComponentInfo info;
		info.name = "BoxCollider ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["center"].type = "glm::vec3";
		info.fields["center"].tooltip = "The center of the collider.";
		info.fields["half_widths"].type = "glm::vec3";
		info.fields["half_widths"].tooltip = "Half the width of the box for each axis.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Camera ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["front"].type = "glm::vec3";
		info.fields["front"].tooltip = "Front vector of the camera.";
		info.fields["up"].type = "glm::vec3";
		info.fields["up"].tooltip = "Up vector of the camera.";
		info.fields["fov"].type = "float";
		info.fields["fov"].tooltip = "Camera field of view (in degrees).";
		info.fields["viewport_id"].type = "unsigned int";
		info.fields["viewport_id"].tooltip = "Id of the viewport that this camera is assigned to.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "CameraZoomController ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["zoom_speed"].type = "float";
		info.fields["zoom_speed"].tooltip = "The speed of the zoom. Note that zoom corresponds to FOV.";
		info.fields["min_zoom"].type = "float";
		info.fields["min_zoom"].tooltip = "Minimum zoom in degrees. Always greater than zero.";
		info.fields["max_zoom"].type = "float";
		info.fields["max_zoom"].tooltip = "Maximum zoom in degrees. Has to be smaller than 180";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Canvas ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["position"].type = "glm::vec2";
		info.fields["position"].tooltip = "The position of the canvas in 2D screen coordinates ranging from 0 to 1. Left top is (0, 0).";
		info.fields["size"].type = "glm::vec2";
		info.fields["size"].tooltip = "Size of the canvas relative to the screen size.";
		info.fields["opacity"].type = "float";
		info.fields["opacity"].tooltip = "Opacity of the UI overlay drawn on this canvas.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "ClickEffect ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["sound_effect"].type = "Resource<audeo::SoundSource>";
		info.fields["sound_effect"].tooltip = "Sound effect to play on mouse click.";
		info.fields["max_distance"].type = "float";
		info.fields["max_distance"].tooltip = "The maximum distance the effect can be heard from.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "ColliderRenderer ";
		info.default_serialize = true;
		info.hide_in_editor = true;
		info.editor_only = false;
		
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "DirectionalLight ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["ambient"].type = "Saturn::color3";
		info.fields["ambient"].tooltip = "Ambient light color.";
		info.fields["diffuse"].type = "Saturn::color3";
		info.fields["diffuse"].tooltip = "Diffuse light color.";
		info.fields["specular"].type = "Saturn::color3";
		info.fields["specular"].tooltip = "Specular light color.";
		info.fields["direction"].type = "glm::vec3";
		info.fields["direction"].tooltip = "Light direction vector.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "DoNotSerialize ";
		info.default_serialize = false;
		info.hide_in_editor = true;
		info.editor_only = false;
		
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "EditorCameraController ";
		info.default_serialize = true;
		info.hide_in_editor = true;
		info.editor_only = false;
		info.fields["speed"].type = "float";
		info.fields["speed"].tooltip = "";
		info.fields["sensitivity"].type = "float";
		info.fields["sensitivity"].tooltip = "";
		info.fields["zoom_speed"].type = "float";
		info.fields["zoom_speed"].tooltip = "";
		info.fields["invert_x"].type = "bool";
		info.fields["invert_x"].tooltip = "";
		info.fields["invert_y"].type = "bool";
		info.fields["invert_y"].tooltip = "";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "FPSCameraController ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["speed"].type = "float";
		info.fields["speed"].tooltip = "The movement speed";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "FreeLookController ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["mouse_sensitivity"].type = "float";
		info.fields["mouse_sensitivity"].tooltip = "The sensitivity of the mouse controller";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Image ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["image"].type = "Resource<Saturn::Texture>";
		info.fields["image"].tooltip = "The image to display.";
		info.fields["position"].type = "glm::vec2";
		info.fields["position"].tooltip = "Position on the UI canvas, relative to it's size.";
		info.fields["anchor"].type = "ui_anchors::anchor_t";
		info.fields["anchor"].tooltip = "UI anchor to align the image with.";
		info.fields["size"].type = "glm::vec2";
		info.fields["size"].tooltip = "Size of the image.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Material ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["diffuse_map"].type = "Resource<Saturn::Texture>";
		info.fields["diffuse_map"].tooltip = "Diffuse texture map.";
		info.fields["shader"].type = "Resource<Saturn::Shader>";
		info.fields["shader"].tooltip = "The shader this material will use.";
		info.fields["lit"].type = "bool";
		info.fields["lit"].tooltip = "Whether this material is affected by lighting.";
		info.fields["specular_map"].type = "Resource<Saturn::Texture>";
		info.fields["specular_map"].tooltip = "Specular texture map.";
		info.fields["normal_map"].type = "Resource<Saturn::Texture>";
		info.fields["normal_map"].tooltip = "Normal map texture.";
		info.fields["shininess"].type = "float";
		info.fields["shininess"].tooltip = "Shininess value of the material";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "MusicController ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["music"].type = "Resource<audeo::SoundSource>";
		info.fields["music"].tooltip = "The music source to play.";
		info.fields["loop"].type = "bool";
		info.fields["loop"].tooltip = "Whether to loop the music when it has finished playing.";
		info.fields["fade_in_ms"].type = "float";
		info.fields["fade_in_ms"].tooltip = "The amount of ms to fade in the music when starting playback.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Name ";
		info.default_serialize = true;
		info.hide_in_editor = true;
		info.editor_only = false;
		info.fields["name"].type = "std::string";
		info.fields["name"].tooltip = "";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "OutlineRenderer ";
		info.default_serialize = true;
		info.hide_in_editor = true;
		info.editor_only = false;
		info.fields["color"].type = "Saturn::color3";
		info.fields["color"].tooltip = "";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "ParticleEmitter ";
		info.default_serialize = false;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["start_size"].type = "glm::vec2";
		info.fields["start_size"].tooltip = "";
		info.fields["life_left"].type = "float";
		info.fields["life_left"].tooltip = "";
		info.fields["direction"].type = "glm::vec3";
		info.fields["direction"].tooltip = "";
		info.fields["velocity"].type = "float";
		info.fields["velocity"].tooltip = "";
		info.fields["enabled"].type = "bool";
		info.fields["enabled"].tooltip = "";
		info.fields["start_velocity"].type = "float";
		info.fields["start_velocity"].tooltip = "";
		info.fields["start_lifetime"].type = "float";
		info.fields["start_lifetime"].tooltip = "";
		info.fields["start_color"].type = "glm::vec4";
		info.fields["start_color"].tooltip = "";
		info.fields["duration"].type = "float";
		info.fields["duration"].tooltip = "";
		info.fields["loop"].type = "bool";
		info.fields["loop"].tooltip = "";
		info.fields["max_particles"].type = "std::size_t";
		info.fields["max_particles"].tooltip = "";
		info.fields["spawn_rate"].type = "float";
		info.fields["spawn_rate"].tooltip = "";
		info.fields["modifier"].type = "Math::Curve";
		info.fields["modifier"].tooltip = "";
		info.fields["gradient"].type = "Saturn::ColorGradient";
		info.fields["gradient"].tooltip = "";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "PointLight ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["ambient"].type = "Saturn::color3";
		info.fields["ambient"].tooltip = "Ambient light color.";
		info.fields["diffuse"].type = "Saturn::color3";
		info.fields["diffuse"].tooltip = "Diffuse light color.";
		info.fields["specular"].type = "Saturn::color3";
		info.fields["specular"].tooltip = "Specular light color.";
		info.fields["intensity"].type = "float";
		info.fields["intensity"].tooltip = "Light intensity.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Rigidbody ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["mass"].type = "float";
		info.fields["mass"].tooltip = "The mass of the rigid body.";
		info.fields["locked_axes"].type = "glm::bvec3";
		info.fields["locked_axes"].tooltip = "The axes that should not be affected by the physics system";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Rotator ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["speed"].type = "float";
		info.fields["speed"].tooltip = "Speed at which to rotate";
		info.fields["euler_angles"].type = "glm::vec3";
		info.fields["euler_angles"].tooltip = "The angles around which to rotate (in degrees).";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Sound ";
		info.default_serialize = false;
		info.hide_in_editor = false;
		info.editor_only = false;
		
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "SoundListener ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["forward"].type = "glm::vec3";
		info.fields["forward"].tooltip = "The forward vector of the listener";
		info.fields["position"].type = "glm::vec3";
		info.fields["position"].tooltip = "Position of the sound listener, relatieve to the entity position";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "SpotLight ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["inner_angle"].type = "float";
		info.fields["inner_angle"].tooltip = "This is where the intensity will begin to fade out. (in degrees).";
		info.fields["ambient"].type = "Saturn::color3";
		info.fields["ambient"].tooltip = "Ambient light color.";
		info.fields["diffuse"].type = "Saturn::color3";
		info.fields["diffuse"].tooltip = "Diffuse light color.";
		info.fields["specular"].type = "Saturn::color3";
		info.fields["specular"].tooltip = "Specular light color.";
		info.fields["intensity"].type = "float";
		info.fields["intensity"].tooltip = "Light intensity.";
		info.fields["direction"].type = "glm::vec3";
		info.fields["direction"].tooltip = "Directin in which the light shines.";
		info.fields["outer_angle"].type = "float";
		info.fields["outer_angle"].tooltip = "This is where the intensity will be completely faded out. (in degrees).";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "StaticMesh ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["mesh"].type = "Resource<Saturn::Mesh>";
		info.fields["mesh"].tooltip = "The mesh resource that will be rendered";
		info.fields["face_cull"].type = "bool";
		info.fields["face_cull"].tooltip = "Whether to do face culling on the mesh. Usually you want this, except for planes.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Text ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["text"].type = "std::string";
		info.fields["text"].tooltip = "The text string to display.";
		info.fields["position"].type = "glm::vec2";
		info.fields["position"].tooltip = "Position on the UI canvas, relative to it's size.";
		info.fields["anchor"].type = "ui_anchors::anchor_t";
		info.fields["anchor"].tooltip = "UI anchor to align the text with.";
		info.fields["size"].type = "glm::vec2";
		info.fields["size"].tooltip = "Size of the text.";
		info.fields["font"].type = "Resource<Saturn::Font>";
		info.fields["font"].tooltip = "Font resource to render the text with.";
		info.fields["color"].type = "Saturn::color3";
		info.fields["color"].tooltip = "Text color.";
		data.push_back(info);
	}
	{
		ComponentInfo info;
		info.name = "Transform ";
		info.default_serialize = true;
		info.hide_in_editor = false;
		info.editor_only = false;
		info.fields["position"].type = "glm::vec3";
		info.fields["position"].tooltip = "Position of the entity in world space, or relative to its parent.";
		info.fields["rotation"].type = "glm::vec3";
		info.fields["rotation"].tooltip = "Rotation of the entity in euler angles (relative to parent).";
		info.fields["scale"].type = "glm::vec3";
		info.fields["scale"].tooltip = "Scale of the entity, independent of parent.";
		data.push_back(info);
	}
}


} // namespace Saturn::Meta::detail
